### ISSUE TITLE
 Handsome 主题8.4.1无法使用该插件。启用后sitemap.xml为空白

### ISSUE THREAD

**Issue by mengdahuang** [xzz-mifan/typecho-sitemap-plugin#1]
Handsome 主题8.4.1无法使用该插件。启用后sitemap.xml为空白

**Comment by IAmJavaEngineer** [comment]
> 

你怎么解决的，我也是handsome主题，也用不了了

**Comment by IAmJavaEngineer** [comment]
> 
我后台都没了

**Comment by xzz-mifan** [comment]
估计有冲突

> Handsome 主题8.4.1无法使用该插件。启用后sitemap.xml为空白

**Comment by xzz-mifan** [comment]
> > 
> 
> 你怎么解决的，我也是handsome主题，也用不了了

也是最新版吗

**Comment by mengdahuang** [comment]
closed
