### ISSUE TITLE
向Google Search Console添加地图后，提示站点地图可读取，但存在错误

### ISSUE THREAD

**Issue by devopssdoc** [xzz-mifan/typecho-sitemap-plugin#3]
![Snipaste_2024-01-05_15-15-58](https://github.com/xzz-mifan/typecho-sitemap-plugin/assets/23027443/3f1592b9-048e-439e-a133-fb4005503104)
向Google Search Console添加地图后，提示站点地图可读取，但存在错误

**Comment by devopssdoc** [comment]
> [https://picture.mhick.com/Snipaste_2024-01-05_15-15-58.png](url)

**Comment by zorrose82** [comment]
SiteMapLogic.php  35行
            "\t\t<lastmod>" . date('Y-m-d\TH:i:s', $lastmod) . "</lastmod>\n" .
改成
            "\t\t<lastmod>" . gmdate('Y-m-d\TH:i:s', $lastmod) . 'Z' . "</lastmod>\n" .
